### ISSUE TITLE
这些新特性为什么没有合并到luban这个库呢

### ISSUE THREAD

**Issue by tianzhijiexian** [shaohui10086/AdvancedLuban#1]

**Comment by shaohui10086** [comment]
因为解决的问题不太一样，Luban 解决的是压缩效率的问题，而 AdvancedLuban 更注重让压缩图片使用更加方便，现在的部分压缩逻辑是使用 Luban 的原有方法实现，未来可能会扩展， 已经确定要做的多图并行压缩，在现有的 Luban 中实现，改动可能会很大，所以最后决定单独维护

**Comment by tianzhijiexian** [comment]
嗯嗯，明白了。
