### ISSUE TITLE
多图批量压缩

### ISSUE THREAD

**Issue by Cwj1992** [shaohui10086/AdvancedLuban#10]
在进行多图压缩的时候，返回的List<File> 虽然每个File的名字都不一样，所有的File打开来看之后，其实是同一张图片或者存在多张一样的图片（压缩之前的图片都是不同的）。

**Comment by shaohui10086** [comment]
你用的是哪个版本的，升级到1.2.7会解决这个问题

**Comment by Cwj1992** [comment]
我使用的是1.2.8，不好意思，回复晚了

**Comment by shaohui10086** [comment]
方便给段代码吗
