### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by juemuren4449** [shaohui10086/AdvancedLuban#23]
混淆之后报错Caused by: java.lang.NoSuchFieldException: No field producerIndex in class Lc/e/e/b/n;
在混淆规则里添加-keep class me.shaohui.advancedluban.**{*;}仍然报错，请问怎么解决？谢谢！

**Comment by shaohui10086** [comment]
不用配置混淆啊，我这边没有额外增加混淆规则也是可以运行的，你检查一下，是AdvancedLuban导致的的吗？

**Comment by juemuren4449** [comment]
在luban那边看到的，添加下面的规则之后就不报错了，应该是rx的问题，还是谢谢了
-dontwarn sun.misc.**
-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
   long producerIndex;
   long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}

**Comment by shaohui10086** [comment]
感谢反馈！

**Comment by SheepYang1993** [comment]
```
-dontwarn sun.misc.**
-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
 long producerIndex;
 long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
 rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
 rx.internal.util.atomic.LinkedQueueNode consumerNode;
}
```
混淆改了一下才成功， 
`rx.internal.util.unsafe.ArrayQueueField*`
改成
`rx.internal.util.unsafe.*ArrayQueue*Field*`
