### ISSUE TITLE
我的项目中其他的库引用了RXJAVA-2.0.0冲突了怎么解决？

### ISSUE THREAD

**Issue by umeitime** [shaohui10086/AdvancedLuban#27]
我的项目中其他的库引用了RXJAVA-2.0.0冲突了怎么解决？

**Comment by shaohui10086** [comment]
Rxjava 1.x 和 2.x 之间理论上是没有冲突的，可以同时引用的，你试过了不行吗？你指的其他库是哪个，我调试一下
