### ISSUE TITLE
lanuch回调线程写错了吧？

### ISSUE THREAD

**Issue by IdioticMadman** [shaohui10086/AdvancedLuban#28]
https://github.com/shaohui10086/AdvancedLuban/blob/master/library/src/main/java/me/shaohui/advancedluban/Luban.java#L129
https://github.com/shaohui10086/AdvancedLuban/blob/master/library/src/main/java/me/shaohui/advancedluban/Luban.java#L152

不应该是observeOn主线程么

**Comment by IdioticMadman** [comment]
![image](https://cloud.githubusercontent.com/assets/16788980/21599347/46d311e2-d1a6-11e6-92e2-035835843dc8.png)
好像这个bitmap也没有被回收掉。

**Comment by shaohui10086** [comment]
确实，应该是observeOn的...改正了，下个版本修正一下，bitmap应该都回收了的，你试下用`CUSTOM_GEAR`,看会不会还出现这样的问题

**Comment by IdioticMadman** [comment]
嗯嗯，试过了可以了
