### ISSUE TITLE
能否添加对压缩后图片重命名的方法

### ISSUE THREAD

**Issue by conghuahuadan** [shaohui10086/AdvancedLuban#29]
你好，能否添加对压缩后图片重命名的方法？（包括单个图片和图片集合），主要解决图片中文名无法上传到服务器的问题

**Comment by shaohui10086** [comment]
之前确实考虑过增加这个功能，但是是实际操作中发现，如果给图片列表都重命名的话，传值是一个很麻烦的事，一般应该没人会选择这么干的，所以建议你在压缩完之后使用系统API重命名：
```
file.rename()
```
