### ISSUE TITLE
压缩条件疑问

### ISSUE THREAD

**Issue by xwpeng** [shaohui10086/AdvancedLuban#3]
一张png图实际大小不高，转成BitMap占用内存也不高，但是尺寸有点大．如果压缩，就会严重失真，这种情况怎么处理．源码压缩条件没有考虑到．
　　也就是说，有些图片Bitmap后实际占用内存不大，不需要压缩，一压缩就严重失真．

**Comment by shaohui10086** [comment]
是用的哪种压缩模式？CUSTOM 还是 THRID, 方便的话可以把测试的图片发给我，我试一下

**Comment by xwpeng** [comment]
THRID,
![abc](https://cloud.githubusercontent.com/assets/13898849/19335734/069fe504-9138-11e6-9c28-f16d50207d76.png)

**Comment by shaohui10086** [comment]
可以考虑换用 CUSTOM，因为 THRID 没有考虑到这种情况，建议换用 CUSTOM ，设置maxSize，这样图片大小小于maxSize的话，就不会压缩，应该可以解决你说的失真的问题。如果还有什么问题，欢迎反馈o(￣▽￣)ｄ

**Comment by xwpeng** [comment]
行，maxSize能解决一部分问题．我可以设置200kb内不压缩，在5.0上运行内存都较大应该没问题．可能我要根据机型的最大内存来设置maxSize.
压缩图片是不希望oom．转成bitmap占用的内存size，尺寸，格式etc都会有影响．

**Comment by xwpeng** [comment]
系统这种压缩，力度不好控制，１/４，１/１６，1/６４．．．
