### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by wangshaolei** [shaohui10086/AdvancedLuban#32]
1 rxjava bug, change thread error.
Observable<File> singleAction(final File file) {
        return Observable.fromCallable(new Callable<File>() {
            @Override
            public File call() throws Exception {
                return compressImage(mLuban.gear, file);
            }
        }).subscribeOn(Schedulers.computation()).observeOn(AndroidSchedulers.mainThread());
    }
2 customCompress about pic's 16:9 error
thanks~ @shaohui10086

**Comment by shaohui10086** [comment]
第一个问题马上解决一下，第二个问题我刚才测试了下没有发现问题，16：9和9:16我都试了下，方便的话， 可以发下出错的那张图片
