### ISSUE TITLE
在LubanCompresser类中compress(String imagePath, int width, int height)方法的问题

### ISSUE THREAD

**Issue by hefugu136234** [shaohui10086/AdvancedLuban#33]
每次图片压缩，进入这个方法，返回的Bitmap都是null，是什么原因

**Comment by shaohui10086** [comment]
我检查一下

**Comment by hefugu136234** [comment]
建议作者去看看Curzibn/Luban 中/library/src/Luban  中对应的相应方法，有变化和不一样的地方

**Comment by hefugu136234** [comment]
不好意思，是我自己的问题。我本来是将压缩后的图片删除，但是有的图片没有压缩，这样我没判断，就删除原图片，导致下次压缩就出错了，检测不到该图片。之前没搞清楚

**Comment by shaohui10086** [comment]
嗯，问题解决了就好
