### ISSUE TITLE
压缩图片存储路径的问题

### ISSUE THREAD

**Issue by yuanxiaofan** [shaohui10086/AdvancedLuban#36]
之前版本是有设置压缩存储路径的，怎么后面版本没有了，默认都是data/data/...假如把文件存到内部存储中再复制出来，然后再clean缓存我觉得可能太多余了，在图片比较多的情况下，会显得更耗时，建议使用更灵活的配置满足不同的需求。

**Comment by shaohui10086** [comment]
你可以试用下1.3.5，支持了自定义缓存目录

**Comment by yuanxiaofan** [comment]
好的，我看见了，之前没发现compress的其他重载方法有定义缓存路径，麻烦你了，谢谢你的分享
