### ISSUE TITLE
请问压缩后的图片文件存在哪里的，怎么删除呢

### ISSUE THREAD

**Issue by 348476129** [shaohui10086/AdvancedLuban#4]

**Comment by shaohui10086** [comment]
压缩后的文件是放在应用数据的cache目录下的，其他应用不可见，当然想要分享的话还是可以通过FileProvider共享出去，应用内不应该不需要手动清理生成的图片的，如果你有想删除的话，v1.1.3增加了一个clearCache的方法，你可以通过下面的代码是清理这些文件：
```
Luban.get(context).clearCache();
```
