### ISSUE TITLE
横向长图压缩完后变得超级小

### ISSUE THREAD

**Issue by qstumn** [shaohui10086/AdvancedLuban#7]
您好，在压缩横向的超长图时，我的一个23776_3568分辨率的图片被压成1009_153，特别的模糊，几乎设么都看不见了，设置成THIRD_GEAR也没什么作用
想请教下怎么解决这个问题

**Comment by shaohui10086** [comment]
因为目前的压缩策略是先检查原文件的大小和最终需要的大小，然后压缩分辨率，然后再开始压缩图片质量，对于这种超长图，在压缩完分辨率之后就已经不能看了，所以目前没有办法解决。对与这种情况，你只能自己判断，如果是超长图而且文件大小过大，自己进行图片质量的压缩，这样分辨率就可以保证

**Comment by qstumn** [comment]
压缩纵向的超长图就没有问题，我把图片旋转成3568x23776后就变成了993x6620，这样的分辨率还是很清晰的

**Comment by shaohui10086** [comment]
刚才看了下，原Luban的那个算法确实有些问题，尝试修改了下，你试下用1.2.8版本，应该修复了这个问题，谢谢你的反馈

**Comment by qstumn** [comment]
横向超长图可以了，很清晰，非常感谢您的算法！

**Comment by shaohui10086** [comment]
客气啦(/≧▽≦)/，还是要谢谢你的反馈的
