### ISSUE TITLE
压塑后的file 再转为bitmap 发现尺寸和size 又是原来的此存

### ISSUE THREAD

**Issue by wei3** [shaohui10086/AdvancedLuban#8]
之前是传base64字符串给服务器的，但因为总是bitmap压塑效果不明显（需求在300-400kB）,又不能裁剪原图片的尺寸，后用了您的压塑框架，是从path --> file -->bitmap -->base64 传给服务器，在file的时候file.length 是符合项目需求的，但下载下来网络上传的图片 大小又和没压塑之前一样了，还有通过file.getAbsolutePath() 获取bitmap 时，bitmap == null 
楼主能否给一些提示，谢谢

**Comment by shaohui10086** [comment]
上传的时候是不是用的最后压缩完成的File呢？可以检查一下最后生成的File的path，压缩后图片的路径应该是在data/data/yourPackageName/cache目录下，
