### ISSUE TITLE
多文件压缩，会返回相同的文件路径

### ISSUE THREAD

**Issue by SheepYang1993** [shaohui10086/AdvancedLuban#9]
压缩的路径是根据时间戳来命名的？多文件压缩，会返回相同的文件路径。。。下面是4张不同的图片多图压缩后返回的路径：
压缩后 file path:/data/user/0/com.xxxx.bbb/cache/luban_disk_cache/1477981667061.jpg
压缩后 file path:/data/user/0/com.xxxx.bbb/cache/luban_disk_cache/1477981667061.jpg
压缩后 file path:/data/user/0/com.xxxx.bbb/cache/luban_disk_cache/1477981667062.jpg
压缩后 file path:/data/user/0/com.xxxx.bbb/cache/luban_disk_cache/1477981667063.jpg

**Comment by SheepYang1993** [comment]
建议多图压缩也可以设置缓存文件名

**Comment by SheepYang1993** [comment]
建议多图弄个设置filename的方法，用时间戳命名同时压缩完就覆盖掉之前的文件了

**Comment by shaohui10086** [comment]
你用的是哪个版本？这个问题在后面的版本应该修复了，没记错的话，应该是1.2.7修复了这个问题，把多图压缩改成串行，解决了文件名重复的问题，其实主要还是多图并行压缩容易出现OOM

**Comment by SheepYang1993** [comment]
嗯，1.2.7修复了，我之前用的1.2.5
